version: "3"

services: 
  api:
    image: link-api-test
    build: .
    command: npm start
    ports: 
      - "3000:3000"
    volumes: 
      - .:/usr/src/app
    depends_on:
      - mongo
    networks: 
      - link-api

  mongo: 
    image: mongo
    ports:
      - "27017:27017"
    networks: 
      - link-api

networks:
  link-api:
    driver: bridge